language: go

go:
  - 1.8

#node_js:
#  - #language version
#
#services:
#  - #any supported service
#
env:

#matrix:

build:
#  pre_ci:
#
#  pre_ci_boot:
#    image_name:
#    image_tag:
#    pull:
#    options:

  ci:
    - TEST_RESULTS_DIR=./shippable/testresults
    - COVERAGE_DIR=./shippable/codecoverage
    - PATH=$PATH:$GOPATH/bin

    - go get -u github.com/jstemmer/go-junit-report
    - go get -u github.com/axw/gocov/...
    - go get -u github.com/AlekSi/gocov-xml

    - mkdir -p $TEST_RESULTS_DIR
    - mkdir -p $COVERAGE_DIR

    - go get -v ./...
    - go get -t -v ./...

    - go test -v -coverprofile=coverage.out ... | tee test.out
    - cat test.out | go-junit-report > $TEST_RESULTS_DIR/report.xml
    - gocov convert coverage.out | gocov-xml > $COVERAGE_DIR/report.xml

#  post_ci:
#    - #command1
#    - #command2
#
#  on_success:
#    - #command1
#    - #command2
#
#  on_failure:
#    - #command1
#    - #command2
#
#  cache:
#  cache_dir_list:
#    - #dir1
#  push:
#
#integrations:
# notifications:
#   - integrationName:
#     type:
#     recipients:
#       - #recp1
#       - #recp2
#
#  hub:
#    - integrationName:
#      type:
#      agent_only: