language: go

go:
  - 1.8

#node_js:
#  - #language version
#
#services:
#  - #any supported service
#
env:
  - PROTOBUF_DL_URL=https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip PROTOC=~/protoc

#matrix:

build:
#  pre_ci:
#
#  pre_ci_boot:
#    image_name:
#    image_tag:
#    pull:
#    options:

  ci:
#    - wget $PROTOBUF_DL_URL
#    - unzip protoc-* -d $PROTOC
#    - export PATH=$PATH:$PROTOC/bin
#
#    - go get -u -v google.golang.org/grpc
#    - go get -u -v github.com/golang/protobuf/{proto,protoc-gen-go}
#    - export PATH=$PATH:$GOPATH/bin

#    - go generate -x
    - go get -v ./...
    - go get -t -v ./...
    - go test -v ./...

#  post_ci:
#    - #command1
#    - #command2
#
#  on_success:
#    - #command1
#    - #command2
#
#  on_failure:
#    - #command1
#    - #command2
#
#  cache:
#  cache_dir_list:
#    - #dir1
#  push:
#
#integrations:
# notifications:
#   - integrationName:
#     type:
#     recipients:
#       - #recp1
#       - #recp2
#
#  hub:
#    - integrationName:
#      type:
#      agent_only: